server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/wiput/Programming/spring-cloud-config/src/main/resources/config/microservice